# Basic Parameters.
bin_size: 0.05 # bins for stimulus voltages (in V). default is 0.05.
time_window: 12.0 # window of EMG time to plot (in ms). default is 10.

# Plot Style Parameters.
title_font_size : 16
axis_label_font_size : 16
tick_font_size : 14
m_color : 'red' # (str) color of M-response flags and plots.
h_color : 'blue' # (str) color of H-reflex flags and plots.
flag_style : ':' # (str) matplotlib linestyle character(s) for H/M-response flags.

# Reflex Parameters
m_start: # (in ms). default is 2.0.
  - 1.0
  - 1.2
m_end: # (in ms). default is 4.0.
  - 3.1
  - 3.3 
h_start: # (in ms). default is 4.1.
  - 4.5
  - 3.8
h_end: # (in ms). default is 7.0.
  - 6
  - 4.5
