# This YAML file contains the configuration parameters for the MonStim_CSV_Analysis program.

# Basic Parameters.
bin_size: 0.05 # bins for stimulus voltages (in V). default is 0.05.
time_window: 8.0 # window of EMG time to plot (in ms). default is 10.
default_method: 'rms' # (str) default method for EMG analysis. default is 'rms'.
default_channel_names: # (list) default channel names for EMG analysis. default is ['LG', 'TA'].
  - 'LG'
  - 'TA'

# EMG Filter Parameters.
butter_filter_args: # dict for butter_bandpass_filter() function. default is below.
  lowcut: 100 # (int) lowcut frequency (in Hz).
  highcut: 3500 # (int) highcut frequency (in Hz).
  order: 4 # (int) order of the filter.

# M-max Caluculation Parameters.
m_max_args: # dict for get_avg_mmax() function. default is below.
  max_window_size: 15 # (int) maximum floating window size for M-max detection (in datapoints).
  min_window_size: 2 # (int) minimum floating window size for M-max detection (in datapoints).
  threshold: 0.2  # (float) standard deviation threshold for M-max detection, default is 0.2.

# Plot Style Parameters.
title_font_size : 16 # (int) font size of the plot title.
axis_label_font_size : 16 # (int) font size of the axis labels.
tick_font_size : 14 # (int) font size of the axis ticks.
m_color : 'red' # (str) color of M-response flags and plots.
h_color : 'blue' # (str) color of H-reflex flags and plots.
flag_style : ':' # (str) matplotlib linestyle character(s) for H/M-response flags.
subplot_adjust_args: # dict fot subplots_adjust() function. default is below.
  left: 0.1
  right: 0.9
  bottom: 0.15
  top: 0.85
  wspace: 0.1
  hspace : 0.5

# Reflex Parameters
m_start: # (in ms). default is 1.0.
  - 1.1
  - 1
m_duration: 2 # (in ms). default is 2.0.

h_start: # (in ms). default is 4.1.
  - 3.3
  - 3.4
h_duration: 1 # (in ms). default is 1.0.

h_threshold: 0.5 # (in mV). default is 0.5.

