# Basic Parameters.
bin_size: 0.2 # bins for stimulus voltages (in V). default is 0.5.
time_window: 10.0 # window of EMG time to plot (in ms). default is 10.

# Reflex Parameters
m_start: 3.0 # (in ms). default is 2.0.
m_end: 5.0 # (in ms). default is 4.0.
h_start: 5.0 # (in ms). default is 4.1.
h_end: 6.5 # (in ms). default is 7.0.
