name: monstim
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy=2.4.*
  - pandas=3.*
  - matplotlib-base=3.10.*
  - scipy=1.17.*
  - h5py=3.16.*
  - pyyaml=6.0.*
  - packaging=26.*
  - traitlets=5.15.*
  - pillow=12.2.*
  - pyside6=6.9.*
  - pyqtgraph=0.14.*
  - pip
  - pip:
      - Markdown==3.10
      - python_markdown_math==0.9
      - pytest==9.1.0
      - setuptools==82.0.1
