# To create/update this environment, run:
#   conda env create -f environment.yml

# To fully re-build the environment from scratch, run:
#   conda env remove -n monstim
#   conda clean --all
#   conda env create -f environment.yml

name: monstim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14.*
  - numpy=2.5.0
  - pandas=3.0.3
  - matplotlib-base=3.10.9
  - scipy=1.18.0
  - h5py=3.16.0
  - pyyaml=6.0.3
  - packaging=26.2
  - traitlets=5.15.1
  - pillow=12.2.0
  - pyside6=6.9.3
  - pyqtgraph=0.14.0
  - pip
  - pip:
      - openpyxl>=3.1
      - Markdown==3.10.2
      - python_markdown_math==0.9
      - pytest==9.1.1
      - setuptools==82.0.1


