name: Bug Report
description: Report a bug or issue with MonStim Analyzer
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using the latest version of MonStim Analyzer
          required: true
        - label: I have checked the documentation and FAQ
          required: true

  - type: input
    id: version
    attributes:
      label: MonStim Analyzer Version
      description: What version of MonStim Analyzer are you using?
      placeholder: "v0.4.2"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Windows 10, Windows 11, macOS 13.0, Ubuntu 22.04, etc."
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The application crashes when..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the behavior
      placeholder: |
        1. Open MonStim Analyzer
        2. Import an experiment from '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: "The application should..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: "Instead, the application..."
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages or Screenshots
      description: |
        If applicable, add error messages or screenshots to help explain your problem.
        You can find log files using Help > Open Log Folder in the application.
      placeholder: "Paste error messages here or drag and drop screenshots"

  - type: dropdown
    id: data-type
    attributes:
      label: Data-related Issue?
      description: Is this issue related to importing or processing specific data?
      options:
        - "No, general application issue"
        - "Yes, issue with data import"
        - "Yes, issue with data processing"
        - "Yes, issue with specific file format"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: data-info
    attributes:
      label: Data Information (if applicable)
      description: |
        If this is a data-related issue, please provide information about your data:
        - File sizes and formats
        - Number of experiments/datasets/sessions
        - Any unusual characteristics
        - Sample file structure (if possible to share)
      placeholder: |
        - CSV files, ~50MB each
        - 3 experiments, 5 datasets each
        - Some sessions have missing channels
        - File structure: Experiment1/Dataset1/Session1-1.csv, etc.

  - type: textarea
    id: analysis-profile
    attributes:
      label: Analysis Profile Settings (if applicable)
      description: |
        If using custom analysis profiles, please describe:
        - Profile name and settings
        - Any custom parameters
        - Latency window configurations
      placeholder: "Using custom profile 'MyProfile' with modified latency windows..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This issue started happening after..."

  - type: checkboxes
    id: support-agreement
    attributes:
      label: Support
      description: Please check the following
      options:
        - label: I am willing to test potential fixes
        - label: I can provide sample data files (if relevant and possible)
        - label: I understand this is open-source software maintained by researchers
