# This YAML file contains the configuration parameters for the MonStim_CSV_Analysis program.

# Basic Parameters.
bin_size: 0.01 # bins for stimulus voltages (in V). default is 0.01.
time_window: 8.0 # window of EMG time to plot (in ms). default is 8-10.
pre_stim_time: 2.0 # amount of pre-stimulus data to plot (in ms). default is 2.0.
default_method: 'rms' # (str) default method for EMG analysis. default is 'rms'.
default_channel_names: # (list) default channel names for EMG analysis. default is ['LG', 'TA'].
  - 'LG'
  - 'TA'
  - 'SOL'

# EMG Filter Parameters.
butter_filter_args: # dict for butter_bandpass_filter() function. default is below.
  lowcut: 100 # (int) lowcut frequency (in Hz).
  highcut: 3500 # (int) highcut frequency (in Hz).
  order: 4 # (int) order of the filter.

# M-max Calculation Parameters.
m_max_args: # dict for get_avg_mmax() function. default is below.
  max_window_size: 15 # (int) maximum floating window size for M-max detection (in datapoints).
  min_window_size: 2 # (int) minimum floating window size for M-max detection (in datapoints).
  threshold: 0.3  # (float) standard deviation threshold for M-max detection, default is 0.3.
  validation_tolerance: 1.05  # (float) tolerance factor for plateau validation (e.g., 1.05 = 5% above plateau mean), default is 1.05.

# Plot Style Parameters.
title_font_size : 16 # (int) font size of the plot title.
axis_label_font_size : 16 # (int) font size of the axis labels.
tick_font_size : 12 # (int) font size of the axis ticks.
m_color : 'tab:red' # (str) color of M-response flags and plots.
h_color : 'tab:blue' # (str) color of H-reflex flags and plots.
latency_window_style : ':' # (str) matplotlib linestyle character(s) for H/M-response flags.
subplot_adjust_args: # dict fot subplots_adjust() function. default is below.
  left: 0.07
  right: 0.93
  bottom: 0.10
  top: 0.90
  wspace: 0.15
  hspace : 0.20

# Reflex Parameters
h_threshold: 0.5 # (in mV). default is 0.5.

preferred_date_format: 'YYMMDD'
latency_window_presets:
  simple_M_H:
    - name: "M-wave"
      start: 0.9
      duration: 1.5
      color: 'tab:red'
      linestyle: ':'
    - name: "H-reflex"
      start: 2.4
      duration: 1.5
      color: 'tab:blue'
      linestyle: ':'
  vibration_H:
    - name: "H1"
      start: -103.5
      duration: 8.5
      color: 'tab:red'
      linestyle: ':'
    - name: "H2"
      start: 46.5
      duration: 8.5
      color: 'tab:blue'
      linestyle: ':'
    - name: "H3"
      start: 196.5
      duration: 8.5
      color: 'tab:green'
      linestyle: ':'
    - name: "H4"
      start: 346.5
      duration: 8.5
      color: 'tab:orange'
      linestyle: ':'

